require 'spec_helper'
require 'models/person'

describe Person do
  subject(:person) { Fabricate(:person) }

  describe '#access_token' do
    it 'has an autogenerated UUID token' do
      expect(person.access_token.length).to eq 36
    end
  end
end
