#!/bin/sh

set -eu

if [ $# -eq 0 ]; then
  echo 'Missing connection string' >&2
  echo "Usage: $0 <connection-string>" >&2
  exit 1
fi

cd "$(dirname "$0")/.."

outfile='db/seeds.sql'
dump_params='-a -O -x --inserts -t faculty_semesters -t semester_periods -t schedule_exceptions'

# shellcheck disable=SC2086
pg_dump "$@" $dump_params > "$outfile.tmp"

# Remove dangerous and incompatible "SET" directives from dump.
sed '/^[sS][eE][tT] \(search_path\|idle_in_transaction_session_timeout\)\s*=/d' "$outfile.tmp" > "$outfile"
rm "$outfile.tmp"

echo "Seeds dumped to $(pwd)/$outfile"
