#!/bin/sh

set -eu

if [ $# -eq 0 ]; then
  echo 'Missing connection string' >&2
  echo "Usage: $0 <connection-string>" >&2
  exit 1
fi

current_dir=$(dirname "$0")
outfile="$current_dir/../db/seeds.sql"
dump_params='-a -O -x --inserts -t faculty_semesters -t semester_periods -t schedule_exceptions'

# shellcheck disable=SC2086
pg_dump "$@" $dump_params > "$outfile"

echo "Seeds dumped to $outfile"
